# Copyright 2010 Petar Maymounkov. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

include $(GOROOT)/src/Make.inc

TARG=github.com/petar/GoLLRB
GOFILES=\
	avgvar.go\
	llrb.go \
	llrb-stats.go \

include $(GOROOT)/src/Make.pkg
